### ISSUE TITLE
Changing neo4j location in env doesn't work

### ISSUE THREAD

**Issue by cbizon** [NCATS-Gamma/robokop#179]
If you change the location of the neo4j in the shared.env file, something in the containers is setting it back to localhost.   If, in program.py, you manually set connection and channel to 0, then it will find the neo4j configured in shared.env.

**Comment by kennethmorton** [comment]
In the robokop-interfaces docker-compose.yml the local env var is set to point to the docker host name instead of honoring the var set in shared.env

NEO4J_HOST=neo4j

This is done because communication from one container (interfaces) to another (neo4j started by manager/helpers) requires that you reference things by the docker name rather than an external name. 

The same thing happens in the robokop-rank docker-compose.yml

I am pretty sure if we delete those lines in each file. They will stop overriding the env vars and will accept the ones from the shared.env and everything should work. 

Patrick can you back me up on this?

**Comment by patrickkwang** [comment]
I think this is right, as long as our neo4j container is publishing all the right ports. When we tie the containers together directly, they don’t have to worry about that. If we publish extra ports we need to make sure everything behind them is password protected.

**Comment by kennethmorton** [comment]
Chris, if you can setup an external neo4j on robokopdb or elsewhere, and we have proper access, I will test locally.

**Comment by patrickkwang** [comment]
The recent deployment overhaul seems to have fixed this.
