### ISSUE TITLE
UI: set node name from label

### ISSUE THREAD

**Issue by cbizon** [NCATS-Gamma/robokop#187]
Currently, in the question construction you can set a "node name".  You can also add a curie, usually by doing a name lookup.  If you add a curie, we should set the node name to the label for the curie.

**Comment by sudeepmandal** [comment]
There are some subtle potential issues with your suggestion. I think we originally left these as intentionally independent things for the following reasons:

1. Curies may not have labels since we allow the user to directly type in something like ABC:123 in the UI and then select that, in which case the curie has no label

2. We also allow the user to pick multiple curies for a node. What would the node name be in this scenario?

3. Some curie names are really long and the node name is ideally a short bit of text that makes sense to the user when viewing the graph structure. The question graphs will likely start looking pretty ugly and weird in many instances with the full text labels for curies

In general, it seems to me that allowing the user to set a custom node name is more flexible but a bit more manual. We can rework it but I'm primarily concerned with points 2 and 3 above.

If we say that by default we should populate it and then let the user override the node name, then there is uncertainty as to when the UI should re-assert auto-populating the "node name" field when the user picks a different curie or adds/deletes a curie.

Thoughts?

**Comment by patrickkwang** [comment]
My main arguments against user-defined labels is that
a) there is no guarantee they are properly associated with the curies - you could accidentally enter "diabetes" and the curie for Ebola, and be very confused forever
b) they are not necessary except for the user's convenience

Let me throw out another crazy option: don't keep human-readable node names in the question at all. They are computationally unnecessary and may cause confusion.

In the GUI, I would show the labels drawn from bionames. Point 3 seems like an issue the GUI will have to handle regardless - a user could easily type in a long name, too. I'm sure we can find a solution to point 2: a semicolon-separated list of the individual curie labels, a comma-separated list of the curies themselves, or something less informative (e.g. disease 1).

**Comment by cbizon** [comment]
I agree - I guess the main point is that we need to dissociate the UI node label from the label element in the question.  Really, the machine question doesn't even need the label, because we will never put it in the answer.

**Comment by sudeepmandal** [comment]
> b) they are not necessary except for the user's convenience
I think that's a big reason to keep it in as a supported feature though. It's obviously not necessary, but it can be very useful to a user, especially if the goal is for the machine question to be a large thing that is handed around where a user may already get some piece from elsewhere. I can easily see the user wanting to custom label a node *if they want to*, with sane defaults for the node labels if they don't provide any. 

To @cbizon 's point, while I agree that we might want to dissociate UI node label from the question since it isn't critical to the processing, I don't see the point in having a node name in the UI which is lost the moment a question is submitted / exported and reimported. At that point you might as well not have it at all. So it feels like the decision is whether we want to keep node names at all, or as @patrickkwang suggested, just toss them out entirely.

@cbizon - Maybe getting user feedback from the folks actually using the interface to play with Robokop might be a good data point to help decide what we should do? I don't care either ways and removing node names shouldn't be a problem, but I do think they serve a valuable purpose to end users.

**Comment by cbizon** [comment]
Agreed on the user feedback - as soon as we have a couple of COP related tickets closed, Alex's students are going to be those users.
