### ISSUE TITLE
Improve Crawler Performance

### ISSUE THREAD

**Issue by cbizon** [NCATS-Gamma/robokop#216]
Even when crawler is just hitting redis and pulling edges from there, it takes a long time to finish everything.   Of course, when it is calling out to things, it's even worse.

In the redis-case, it should be possible to speed this up.  One problem is the simple way crawler is currently implemented.  If e.g. we want to crawl disease-phenotype links, we compile a list of every disease in MONDO, then for each disease d, we do a builder with the question (d)--(phenotypic_feature). 

It works, but we are creating a lot of overhead for each input identifier.  The actual call to redis is probably a tiny fraction of what's taking so long.

A simple thing to try is to pass in a question that looks like:
(d1)--(phenotpyic_feature), (d2)--(phenotpyic_feature), (d3)--(phenopypic_feature).

This question doesn't create a connected graph (necessarily), but that's ok.  Builder doesn't really care.  It just puts d1,d2,and d3 on the program stack and executes them.  Even with nothing else, this reduces the overhead by a factor of however many d's you send in.

The other nice thing here, is that if we make improvements to program such as multithreading or pipelining redis calls, crawler will be able to take advantage of them.

- [x] modify buildmain.run to allow a more complex signature
- [x] test the value of N that gives the best speedup
- [ ] decide whether to pursue further enhancements within program.py

**Comment by YaphetKG** [comment]
Run a couple of tests on the crawler, after updating how the machine question is constructed. So the machine questions are now multiple node pairs in one question, as opposed to a single pair per program. 
When doing tests on this I found something interesting that we do to get the concept graph for a question. This happens when a Question is compiled to a program. There is a Cypher query that will be constructed based on the nodes and edges that we passed through the machine question and then we have our operations populated from the concept graph. Now the issue is when the number of nodes gets higher and higher so does the size of nodes that this query uses. This beyond a certain number of nodes the query starts to lag very seriously. The number of nodes per program that I found to perform well is 10 due to this reason.  I tried with nodes up to 18 but 18 costs more that it profits us so I had to stop there. 
<table>
<tr>
<th>Process Pool Size</th><th>total Ids / Ids sent per program</th><th>Avg time (of three runs)</th>
</tr>
<tr><td rowspan="4">1</td><td>10.0/10</td><td>00:08.2</td></tr>
<tr><td>100/10</td><td>00:29.8</td></tr>
<tr><td>100/15</td><td>01:03.4</td></tr>
<tr><td>18/18</td><td>01.14.6</td></tr>
<tr><td rowspan="4">10</td><td>100/10</td><td>00:37.8</td></tr>
<tr><td>100/1</td><td>01:24.8</td></tr>
<tr><td>1000/10</td><td>03:02.6</td></tr>
<tr><td>1000/1</td><td>14:17.3 (did only 1 run for this)</td></tr>
</table>
All were timed using the pre-populated cache.
I am currently thinking to use 10 per program. And then look for a clean way to increase the query efficiency so it can get the concept graph for such nodes since its going to be same for all of them.
