### ISSUE TITLE
Integrate construction with the UI more

### ISSUE THREAD

**Issue by cbizon** [NCATS-Gamma/robokop#22]
Right now, somebody constructs a path in the UI and then it goes to builder, which decides whether or not the path is valid. But it makes more sense for that validity to be checked in the UI.  Then the UI could be constructed a number of ways:

1) Given two endpoints, show me all the paths that might work and let me pick
2) Given where I am now, give me only the options that are connectable to my current option.

**Comment by patrickkwang** [comment]
To confirm, you anticipate this checking only for concept-graph validity, not for full knowledge-graph validity? The first is typically fast, but the second means basically the entire build process, which is not.

We can check that the named entities can be mapped to identifiers, and that the sequence of concepts has connecting knowledge sources, but we still will not know that a specific entity X can be connected via concepts A and B to entity Y, until we've tried to run the full build.

**Comment by cbizon** [comment]
> To confirm, you anticipate this checking only for concept-graph validity, not for full knowledge-graph validity?

Yes

**Comment by kennethmorton** [comment]
This is important and should be done as we build a new machine question editor.

1.  Manager API endpoint to provide validation and indicate impossible edges
2.  New question editor calls this API endpoint after each edit and updates the UI to show impossibilities.


In the manager API endpoint determining validity requires two checks.

1.  The edge is impossible because of the services between these two types
2.  The edge is impossible given the surrounding question and named entities (not traversable because we can only go certain directions)

For check 2. This is only important for building. It's possible that due to already found graph structure something could fail the traversable check but actually return results. Maybe failing only test 2 results in a warning?

**Comment by cbizon** [comment]
OBE - specifically we don't use builder to answer questions as much in a way that makes this important to follow up on
