### ISSUE TITLE
Need to broaden chemical crawling

### ISSUE THREAD

**Issue by cbizon** [NCATS-Gamma/robokop#231]
To pick up metabolic pathways & chemical reactions, we rely on KEGG, which has it's own compound ids.  We separately query for chemical->chemical and chemical->gene relations, and a reaction from KEGG ends up looking like 3 tuples (A)-[degrades_into]->(B) for the chemicals, and then each chemical related to the gene (one saying the gene makes it and the other says the gene eats it).

The problem with crawling comes up when e.g. B doesn't have a CHEBI id, then it doesn't get crawled, and we cant' form this metabolic link. The KEGG part works, we're just not building in  enough calls. So we should increase the chemical crawling to include any compound that has a KEGG.Compound ID , even if it doesn't have a chebi (the one I'm looking at has hmdb and pubchem and kegg, but not chebi or chembl)

**Comment by YaphetKG** [comment]
As part of this, needed to modify OXO synonymizer to parse down KEGG.COMPOUND:<id> to KEGG:<id> before making synonymization calls.  And since the "id" will be a "C-id" in this case (which in KEGG will be a  compound https://www.kegg.jp/kegg/compound/), it is safe to omit ".COMPOUND" namespace when calling Oxo.

**Comment by YaphetKG** [comment]
http://rest.kegg.jp/list/compound is part of the crawling list. Maybe we can include http://rest.kegg.jp/list/drug ? but for now, starting crawling on compounds.
