### ISSUE TITLE
Failed COP

### ISSUE THREAD

**Issue by karafecho** [NCATS-Gamma/robokop#295]
I attempted to generate a couple of COPs of the following form: chemical substance->gene->biological process or activity-> phenotypic feature->disease.

This one worked:
![image](https://user-images.githubusercontent.com/26254388/56754923-36780c00-675c-11e9-8a81-1621bfff3c92.png)

But a related one didn't:
![image](https://user-images.githubusercontent.com/26254388/56754860-0466aa00-675c-11e9-9f8e-9e7bcd26125e.png)

Not sure why.

**Comment by cbizon** [comment]
I think it's a stereochemistry issue.  Try CHEBI:77733 (the stereochemistry-free identifier)

**Comment by karafecho** [comment]
I can't. The only other option is PUBCHEM:2520.

**Comment by cbizon** [comment]
Just put the CHEBI in directly, instead of the name

**Comment by cbizon** [comment]
Or the PUBCHEM one, that's the same as CHEBI:77733

**Comment by karafecho** [comment]
Oh, yeah. I'm running it now. This is for the CEGS proposal, if you haven't figured that out already. :-)

**Comment by karafecho** [comment]
The query is still running, but I thought I should note that a user would not know to use the ID instead of the natural language term. In other words, users are going to use whatever ID options are provided in response to a natural language text entry.

**Comment by cbizon** [comment]
Right, just to clear up the confusion - you wouldn't have to put in the curie directly.  If you had chosen the pubchem id instead of the chebi one, things would have been fine.   Now, you didn't have any way to know which of the two choices was better.   There are linkouts on the right that try to give you some info, but even if you had gone to them, you wouldn't have found any information as to which of the two options would be better.  

So I think we either need to try to provide info about KG connections in the dialog or run all.  This is further discussed in #306

**Comment by karafecho** [comment]
Agreed. This can be very confusing to users.
