### ISSUE TITLE
Fix neo4j communication

### ISSUE THREAD

**Issue by cbizon** [NCATS-Gamma/robokop#30]
Currently robokop-build and robokop-interface are (I think) using different interfaces to neo4j.  Also, we are not authenticating our neo4j connections, which we should do.

**Comment by patrickkwang** [comment]
robokop uses neo4j-driver, like robokop-build. I had authentication for the Neo4j database but turned it off for some reason, which I do not remember.

**Comment by cbizon** [comment]
It was because there was some trouble with authentication from the greent package, so we had it turned off on the neo4j server.  Whatever the issue was in greent hasn't been sorted out yet, but that's part of the issue.

**Comment by patrickkwang** [comment]
I think we can now re-enable authentication. But I'm not currently sure what it gets us.

Neo4j's not-open-source enterprise edition has user role management tools so that we could make a public-facing read-only guest account in addition to our read/write backend account, but that functionality is unavailable with the community edition. I'm looking into whether we can get a free license, since we're cool and open source.

But if we can't make read-only accounts, all our users will be read/write, and unless we plan to have a public-facing account with full privileges, we might as well not expose those ports, at which point authentication is pointless.

**Comment by patrickkwang** [comment]
The short story is Neo4j user role management is not coming in the foreseeable future. But Neo4j authentication is in place and everyone is using the same bolt interface.
