### ISSUE TITLE
failed to retrieve publication information

### ISSUE THREAD

**Issue by cbizon** [NCATS-Gamma/robokop#301]
Pulling up publications for an edge frequently has a lot of "Failed to retrieve publication information" results.   This seems to be for edges that have a lot of publications.  If there's only a couple, it works fine.

**Comment by maximusunc** [comment]
This is happening because we're trying to fire off requests to the pubmed API way too quickly and we're getting back 429 errors. A couple solutions would be to manually slow down how fast we fire these requests off, but that would make the UI a bit slower and not as smooth, plus scrolling really fast still causes the 429s. The other solution would be to cache all of these queries in a db somewhere and then load them from there, though we might end up with the same 429 issue but just on our end. Lastly, the "cancelable" function in the PubmedEntry component doesn't seem to be working, and that might help the scrolling too fast issue.

Options:
1. Stand up a dedicated DB for pubmed publication info. The UI can then hammer that as fast as we desire.
2. Somehow integrate with Omnicorp?
3. Route the request through our server and use the requests cache or another redis cache

I think we (Kenny and Max) have heard of other groups having an interest in such a DB. Presumably one sort of exists in some form from building omnicorp? Can we just dump relevant information into a postgres? If so that is probably the quickest solution that has more long term benefits. If not, option 3 isn't too difficult. We can just leverage the existing requests cache.

**Comment by maximusunc** [comment]
Option 3 is probably quick enough that we should just do it. Option 1 is preferable but wont realistically be done for a few weeks. Even if it were done we would still probably want to redis cache our requests to it, making option 3 also desired.

So we are going to implement option 3.

**Comment by cbizon** [comment]
I believe that the next round of omnicorp will have this data?  @balhoff will know where that stands.  But I suspect it's not immediate?   But I agree that having it in redis is desirable either way, and it would be nice to have this sorted out relatively quickly.

**Comment by maximusunc** [comment]
Resolved in pull request #317
