### ISSUE TITLE
Login not responding

### ISSUE THREAD

**Issue by gotwals** [NCATS-Gamma/robokop#375]
I have an account (gotwals@ncssm.edu), but login page (https://robokop.renci.org/login/) not responsive.

**Comment by YaphetKG** [comment]
There was an issue with our proxy and flask security configuration combo. proxy rewrite rule was forcing redirects on urls missing trailing '/'. And the login url had been missing a trailing slash, so it was losing the form data sent to it after the rewrite(redirect) by nginx happens.  Fixed by adding trailing slash for the flask security URLs.
