### ISSUE TITLE
expedite blackboard creation

### ISSUE THREAD

**Issue by patrickkwang** [NCATS-Gamma/robokop#6]
New blackboards take a really, really long time to create. - KF

**Comment by patrickkwang** [comment]
My understanding is this is dominated by knowledge source API calls. Especially for COP-like queries, we spend a lot of time looking for edges connecting common intermediate nodes (e.g. immune system to X). I think #7 would help a lot here.

**Comment by cbizon** [comment]
Yes, and there are some other things that could help.  First, the build process itself ends up calling the same functions with the same arguments a fair number of times, because there ends up being a lot of crosstalk in the results.  For a lot of the smartapi style endpoints it's not such a big deal because we are doing some caching of results there, but for the sparql endpoints we are not.  That's mostly because we are just caching using httpcache (or something) and those aren't http calls. 

So we could 1) do caching for the sparql endpoints in a different way and/or fix the build process to avoid multiple calls.  

At the end of the day, though, I think that #7 is the best answer.

**Comment by patrickkwang** [comment]
We have completed the proposed fixes for this, so I'm going to close it. But keeping everything speedy will of course be an ongoing project.
