### ISSUE TITLE
Evidence Sources

### ISSUE THREAD

**Issue by stevencox** [NCATS-Gamma/robokop#72]
During a pre-hackathon review it was observed that a Google search returned a large number of literature hits not seen in a Robokop generated answer graph.

@kennethmorton - could you add info about the question demonstrating this issue?

Alex asks if
* If we removed Chemotext from our support mechanism.
* If so, why
* How we can get fuller literature results.

**Comment by cbizon** [comment]
Support edges can be generated with several methods, and should be configurable to use them either together or independently.  I think that the code for chemotext is a little stale at the moment, so I'm not sure that we can actually do that (but it is the plan that we should be able to).

The basic idea with not worrying too much about it was that we felt like omnicorp was a better source, but that may not be accurate.  Please provide details for what is missing, otherwise it's fairly tough to track down.

**Comment by cbizon** [comment]
There are a couple of issues wrapped up here:

1) Why does biolink return something that omnicorp doesn't?  This is a good question that we should investigate. I expect it has to do with the way labels are being used, and we can dig into it.

2) Is chemotext turned off and can it turn back on?   It is turned off, and that's because it has been subsumed into omnicorp. That is, omnicorp is reading the same mesh annotations that chemotext was, so chemotext should be a subset of omnicorp.    If there are edges that were in chemotext that aren't showing up here, then that's a bug.   HGNC/MONDO example above is not such a case, because chemotext did not contain genes.

**Comment by stevencox** [comment]
@balhoff - here's the issue.

**Comment by balhoff** [comment]
@kennethmorton with HGNC:7897 and MONDO:0009757 OmniCorp returns 65 results. Not so different from 71.

**Comment by balhoff** [comment]
Let's make sure there's not an issue with prefix expansion somewhere.
